package dev.primeremote.core

import dev.primeremote.core.protocol.*
import kotlinx.serialization.json.*
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue

/**
 * Verifies the Kotlin protocol implementation against vectors generated by LEGO's own
 * Python reference implementation (see tools/gen_golden_vectors.py).
 */
class GoldenVectorTest {

    private val golden: JsonObject by lazy {
        val text = javaClass.classLoader!!.getResourceAsStream("golden_vectors.json")!!
            .readBytes().decodeToString()
        Json.parseToJsonElement(text).jsonObject
    }

    private fun String.hexToBytes(): ByteArray {
        val out = ByteArray(length / 2)
        for (i in out.indices) {
            out[i] = ((hexDigit(this[i * 2]) shl 4) or hexDigit(this[i * 2 + 1])).toByte()
        }
        return out
    }

    private fun hexDigit(c: Char): Int = when (c) {
        in '0'..'9' -> c - '0'
        in 'a'..'f' -> c - 'a' + 10
        in 'A'..'F' -> c - 'A' + 10
        else -> error("bad hex digit $c")
    }

    private fun ByteArray.toHex(): String =
        joinToString("") { b ->
            val v = b.toInt() and 0xFF
            "0123456789abcdef"[v shr 4].toString() + "0123456789abcdef"[v and 0xF]
        }

    @Test
    fun `cobs encoding matches LEGO reference`() {
        val vectors = golden["cobs"]!!.jsonArray
        assertTrue(vectors.size >= 15, "expected a decent number of vectors")
        for (v in vectors) {
            val o = v.jsonObject
            val raw = o["raw"]!!.jsonPrimitive.content.hexToBytes()
            val encoded = o["encoded"]!!.jsonPrimitive.content
            val packed = o["packed"]!!.jsonPrimitive.content
            assertEquals(encoded, Cobs.encode(raw).toHex(), "encode(${raw.toHex()})")
            assertEquals(packed, Cobs.pack(raw).toHex(), "pack(${raw.toHex()})")
        }
    }

    @Test
    fun `cobs round trips every vector`() {
        for (v in golden["cobs"]!!.jsonArray) {
            val raw = v.jsonObject["raw"]!!.jsonPrimitive.content.hexToBytes()
            assertEquals(raw.toHex(), Cobs.unpack(Cobs.pack(raw)).toHex())
        }
    }

    @Test
    fun `crc matches LEGO reference`() {
        for (v in golden["crc"]!!.jsonArray) {
            val o = v.jsonObject
            val data = o["data"]!!.jsonPrimitive.content.hexToBytes()
            val seed = o["seed"]!!.jsonPrimitive.long
            val align = o["align"]!!.jsonPrimitive.int
            val expected = o["crc"]!!.jsonPrimitive.long
            assertEquals(expected, Crc.crc32(data, seed, align), "crc(${data.toHex()}, seed=$seed)")
        }
    }

    @Test
    fun `request serialization matches LEGO reference`() {
        val byName = golden["messages"]!!.jsonArray.associate {
            it.jsonObject["name"]!!.jsonPrimitive.content to it.jsonObject
        }

        fun check(name: String, request: HubRequest) {
            val o = byName[name] ?: error("no golden vector named '$name'")
            assertEquals(o["payload"]!!.jsonPrimitive.content, request.serialize().toHex(), "$name payload")
            assertEquals(
                o["framed"]!!.jsonPrimitive.content,
                Cobs.pack(request.serialize()).toHex(),
                "$name framed",
            )
        }

        check("InfoRequest", InfoRequest)
        check("ClearSlotRequest(slot=3)", ClearSlotRequest(3))
        check(
            "StartFileUploadRequest(program.py, slot=19, crc=0x12345678)",
            StartFileUploadRequest("program.py", 19, 0x12345678L),
        )
        check(
            "TransferChunkRequest(crc=0xAABBCCDD)",
            TransferChunkRequest(0xAABBCCDDL, "import runloop\n".encodeToByteArray()),
        )
        check("ProgramFlowRequest(start, slot=19)", ProgramFlowRequest(stop = false, slot = 19))
        check("ProgramFlowRequest(stop, slot=19)", ProgramFlowRequest(stop = true, slot = 19))
        check("DeviceNotificationRequest(200ms)", DeviceNotificationRequest(200))
        check("TunnelMessage", TunnelMessage("mv A 500;mv B -500;".encodeToByteArray()))
        check("SetHubNameRequest", SetHubNameRequest("Rover"))
        check("GetHubNameRequest", GetHubNameRequest)
        check("DeviceUuidRequest", DeviceUuidRequest)
    }

    @Test
    fun `responses deserialize correctly`() {
        val byName = golden["responses"]!!.jsonArray.associate {
            it.jsonObject["name"]!!.jsonPrimitive.content to it.jsonObject
        }

        fun parse(name: String): HubMessage {
            val o = byName[name] ?: error("no golden vector named '$name'")
            // go through the full framing path the BLE layer uses
            val framed = o["framed"]!!.jsonPrimitive.content.hexToBytes()
            val assembler = FrameAssembler()
            val frames = assembler.feed(framed)
            assertEquals(1, frames.size, "$name should produce exactly one frame")
            return Messages.deserialize(Cobs.unpack(frames[0]))
        }

        val info = parse("InfoResponse") as InfoResponse
        assertEquals(3, info.firmwareMajor)
        assertEquals(4, info.firmwareMinor)
        assertEquals(3, info.firmwareBuild)
        assertEquals(20, info.maxPacketSize)
        assertEquals(302, info.maxMessageSize)
        assertEquals(288, info.maxChunkSize)
        assertEquals("3.4.3", info.firmwareVersion)

        assertEquals(StatusResponse(MessageId.CLEAR_SLOT_RESPONSE, true), parse("ClearSlotResponse(ok)"))
        assertEquals(StatusResponse(MessageId.START_FILE_UPLOAD_RESPONSE, true), parse("StartFileUploadResponse(ok)"))
        assertEquals(StatusResponse(MessageId.TRANSFER_CHUNK_RESPONSE, false), parse("TransferChunkResponse(fail)"))
        assertEquals(StatusResponse(MessageId.PROGRAM_FLOW_RESPONSE, true), parse("ProgramFlowResponse(ok)"))
        assertEquals(ProgramFlowNotification(true), parse("ProgramFlowNotification(stop)"))
        assertEquals(ConsoleNotification("!rdy 1 poll"), parse("ConsoleNotification"))

        val dev = parse("DeviceNotification") as DeviceNotification
        assertEquals(7, dev.updates.size)
        assertEquals(DeviceUpdate.Battery(87), dev.updates[0])
        val imu = dev.updates[1] as DeviceUpdate.Imu
        assertEquals(90, imu.yaw)
        assertEquals(-3, imu.pitch)
        assertEquals(980, imu.accelZ)
        val motorA = dev.updates[2] as DeviceUpdate.Motor
        assertEquals(0, motorA.port)
        assertEquals(MotorType.LARGE, motorA.deviceType)
        assertEquals(45, motorA.absolutePosition)
        assertEquals(500, motorA.power)
        assertEquals(42, motorA.speed)
        assertEquals(1234, motorA.position)
        val motorB = dev.updates[3] as DeviceUpdate.Motor
        assertEquals(1, motorB.port)
        assertEquals(MotorType.MEDIUM, motorB.deviceType)
        assertEquals(-45, motorB.absolutePosition)
        assertEquals(-42, motorB.speed)
        assertEquals(-1234, motorB.position)
        assertEquals(DeviceUpdate.Force(port = 2, value = 55, pressed = true), dev.updates[4])
        assertEquals(DeviceUpdate.Color(port = 3, color = 9, red = 300, green = 100, blue = 120), dev.updates[5])
        assertEquals(DeviceUpdate.Distance(port = 4, distance = 137), dev.updates[6])
    }
}
